### Este teste deve gerar 2 traces (trace inicial e trace do serviço chamado)
POST http://localhost:8080/
Host: localhost:8080
Content-Type: application/json

{
  "cep":"00000001"
}

### Este teste deve gerar 1 trace (trace deste serviço apenas)
POST http://localhost:8081/
Host: localhost:8081
Content-Type: application/json

{
"cep":"01311100"
}